### PR TITLE
Fixes issue where initial ui load returns blank page

### LINKED ISSUE #139: The initial load of the UI returns a blank page
**Describe the bug**
The initial load of the UI returns a blank page. After refreshing it loads successfully. 

**Version**
[v0.3.0](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/v0.3.0)

**To Reproduce**

**Expected behavior**
The UI loads successfully on 1st render. 

**Screenshots**
```Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
    at Nt (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1259:478)
    at At (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1259:251)
    at t.instanceFactory (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1275:148)
    at t.getOrInitializeService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:16005)
    at t.getImmediate (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:14525)
    at t.instanceFactory (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1911:2633)
    at t.getOrInitializeService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:16005)
    at t.getImmediate (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:14525)
    at t._getService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1588:176118)
    at t.<computed> [as analytics] (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1604:1190)```
**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome Incognito


**Additional context**
Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by mservidio**
Fixes #139

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

File: frontend/src/main.js [hunk 1]
```diff
@@ -13,39 +13,39 @@ Vue.config.productionTip = false;
...
-
-  new Vue({
-    vuetify,
-    router,
-    store,
-    render: h => h(App)
-  }).$mount('#app');
+// Fetch and load the store settings
+store.dispatch('getSettings').then(() => {
+  // Initialize Firebase with a "default" Firebase project
```
Comment (mservidio) [inline frontend/src/main.js:22]: On the initial load getSettings was on a delay (it's an async function), and the initial for the firebaseConfig was being called before the default settings were set in the store.
