### PR TITLE
Consumers should only see my products

### LINKED ISSUE #189: 'My Products' should be the only visible nav menu item for a marketplace or consumer user
**Describe the bug**
'My Products' should be the only visible nav menu item for a marketplace or consumer user

### PR DESCRIPTION
**Pull request by mservidio**
Fixes #189

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

### CODE REVIEW

File: api/v1alpha/src/admin/index.js [hunk 1]
```diff
@@ -188,4 +188,13 @@ admin.post('/projects/:projectId/admin::custom', async (req, res) => {
     }
 });
 
+admin.get('/projects/:projectId/admin/isAdmin', async(req, res) => {
```
Comment (phriscage) [inline api/v1alpha/src/admin/index.js:191]: I would suggest changing `/admin/isAdmin` to something that closely represents the action of the client and fits a custom HTTP verb logic like e.g POST `/auth::isAdmin`. Also should this map to the name of the admin group [Data Producers](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/master/api#data-producers)

File: api/v1alpha/src/admin/index.js [hunk 2]
```diff
@@ -188,4 +188,13 @@ admin.post('/projects/:projectId/admin::custom', async (req, res) => {
     }
 });
```
Comment (phriscage) [inline api/v1alpha/src/admin/index.js:190]: Can you add the appropriate API documentation here?

**Review by phriscage — COMMENTED** [review]
I think you will need to add the corresponding Istio authz rule [here](https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml#L9) for this logic to integrate to the backend

**Comment by phriscage** [comment]
> I think you will need to add the corresponding Istio authz rule [here](https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml#L9) for this logic to integrate to the backend

I've create a separate request, https://github.com/GoogleCloudPlatform/datashare-toolkit/issues/342, to update this accordingly.

File: api/v1alpha/src/admin/index.js (hunk 1 above)
Comment (mservidio) [reply api/v1alpha/src/admin/index.js:191]: Change to post and making /auth::custom - handle case as 'isDataProducer'.

File: api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml [hunk 3]
```diff
@@ -7,6 +7,31 @@ metadata:
...
+      paths: ["/v1alpha/projects/$PROJECT_ID/policies*, /v1alpha/projects/$PROJECT_ID/policies/*"]
+    - operation:
+      methods: ["GET,POST,PUT,DELETE"]
+      paths: ["/v1alpha/projects/$PROJECT_ID/datasets*, /v1alpha/projects/$PROJECT_ID/datasets/*"]
+    - operation:
+      methods: ["POST"]
+      paths: ["/v1alpha/projects/$PROJECT_ID/admin*, /v1alpha/projects/$PROJECT_ID/admin/*"]
+    - operation:
+      methods: ["POST"]
+      paths: ["/v1alpha/projects/$PROJECT_ID/auth*, /v1alpha/projects/$PROJECT_ID/auth/*"]
```
Comment (phriscage) [inline api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml:25]: I would make this the full URL `/v1alpha/projects/$PROJECT_ID/auth:isDataProducer` otherwise a *Data Producer* has access to all `auth::custom` methods.

File: api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml [hunk 4]
```diff
@@ -7,6 +7,31 @@ metadata:
 spec:
   action: ALLOW
   rules:
+  - to:
+    - operation:
+      methods: ["GET,POST,PUT,DELETE"]
+      paths: ["/v1alpha/projects/$PROJECT_ID/accounts*, /v1alpha/projects/$PROJECT_ID/accounts/*"]
```
Comment (phriscage) [inline api/v1alpha/istio-manifests/1.4/authz/allow-data-producers-policy.yaml:13]: Is a wildcard asterisk '*' is required for both the resource `/accounts*` and the sub resources `/accounts/*` or just the first option?

File: api/v1alpha/src/auth/index.js [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+const express = require('express');
+
+/************************************************************
+  API Endpoints
+ ************************************************************/
+// Define the routes for the REST API
+var auth = express.Router();
+// methods that require multiple routes
+
+auth.post('/projects/:projectId/auth::custom', async (req, res) => {
```
Comment (phriscage) [inline api/v1alpha/src/auth/index.js:28]: Can you add the appropriate OAS API documentation here?

File: api/v1alpha/src/auth/index.js [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+  API Endpoints
+ ************************************************************/
+// Define the routes for the REST API
+var auth = express.Router();
+// methods that require multiple routes
+
+/**
+ * @swagger
+ *
+ * /projects/{projectId}/auth::custom
```
Comment (phriscage) [inline api/v1alpha/src/auth/index.js:31]: This route should be explicit for the OAS documentation, since when a client tries to test in a OAS UI, the sample curl commands will be '/auth::custom' instead of '/auth:isDataProducer'. I was going to reference https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/master/api/v1alpha/src/accounts/index.js#L645, but that needs to be updated too, so I'll create a bug.

File: api/v1alpha/src/auth/index.js [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+
+/**
+ * @swagger
+ *
+ * /projects/{projectId}/auth:isDataProducer:
+ *   get:
+ *     summary: Simple endpoint to check if user is a data producer
+ *     description: Returns a 200 response
+ *     tags:
+ *       - auth
```
Comment (phriscage) [inline api/v1alpha/src/auth/index.js:36]: The new *auth* tag will need to be added to the main index.js for grouping in the OAS: https://github.com/GoogleCloudPlatform/datashare-toolkit/blob/f8b66f0afddc4f164d50e262f6d39206ee716853/api/v1alpha/src/index.js#L130

**Review by phriscage — APPROVED** [review]
lgtm
