### PR TITLE
Error thrown when deleting a dataset

### LINKED ISSUE #357: Error thrown when deleting a dataset
**Describe the bug**
Error: Query column 6 has type ARRAY<STRUCT<datasetId STRING>> which cannot be inserted into column datasets, which has type ARRAY<STRUCT<datasetId STRING, tables ARRAY<STRUCT<tableId STRING>>>>

This broke when we added table support to policies. When deleting a Dataset, related views and policies are re-inserted with the deleted flag. When we update the policies to remove the deleted datasets, the nested table data needs to come along also.

The dataset will still delete from BQ, however any policies that included reference to the Dataset, will still contain a reference to the dataset. As we check for the existence of datasets before applying policies, no error will be thrown during a sync process. This is really just an issue of the data not updating properly.

**To Reproduce**
1. Delete a Dataset through the UI

### PR DESCRIPTION
**Pull request by mservidio**
Fixes #357

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

### CODE REVIEW

File: api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql [hunk 1]
```diff
@@ -43,6 +43,7 @@ policyData AS (
   LEFT JOIN UNNEST(r.datasets) d
   LEFT JOIN UNNEST(d.tables) t
   LEFT JOIN userPolicies p ON r.policyId = p.policyId
+  WHERE d.datasetId IS NOT NULL
```
Comment (mservidio) [inline api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql:46]: To force the procedure to update for now, we can add documentation into the update steps to click the 'Initialize Schema' button after performing the upgrade. Or, we can create a separate button to 'Upgrade Schema', and we can build a separate mechanism to track and apply updates - but we probably need a separate effort for that.

Comment (phriscage) [reply api/v1alpha/src/admin/bq/procedure/permissionsDiff.sql:46]: ok. Let's add a quick note in the README for now and cut a feature request for a more comprehensive upgrade strategy.

**Review by phriscage — APPROVED** [review]
lgtm
